spring.application.name=leave-service
server.port=8006

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/atlas_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:atlas_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:atlas_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
